version: '2'
services:
 mongodb:
  image: mongo:latest
  container_name: mongodb
  ports:
   - "27017:27017"

 mongodb-backup:
  build: ./
  container_name: mongodb-backup
  depends_on:
   - mongodb
  links:
   - mongodb
  volumes:
   - ./backup:/backup
  environment:
   - MONGODB_HOST=mongodb
   - MONGODB_PORT=27017
   - MONGODB_DB=appDB
   - CRON_TIME=* * * * *
   - MAX_BACKUPS=5
   - INIT_RESTORE=TRUE
